import { PaginationResult } from '@/types/api';
import { PostRes } from '@/features/community/types';

export const mockCommunityPosts: PaginationResult<PostRes> = {
  metadata: {
    page: 1,
    limit: 10,
    totalPages: 1,
    totalItems: 10,
  },
  items: [
    {
      id: 'post-1',
      publicId: 'outfit-monochrome-fall-01',
      title: 'Oversized Wool Coat & Wide-leg Trousers',
      content: 'Phối đồ mùa thu đông theo phong cách Minimalist Monochrome. Một chiếc áo măng tô len dạ dáng dài kết hợp quần âu ống rộng xếp ly và boots mũi nhọn.',
      postType: 'OUTFIT',
      userId: 'user-01',
      username: 'elena.rostova',
      firstName: 'Elena',
      lastName: 'Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
      likeCount: 142,
      commentCount: 18,
      isLiked: false,
      isDeleted: false,
      createdAt: '2026-09-24T09:30:00.000Z',
      updatedAt: '2026-09-24T09:30:00.000Z',
      sharePath: '/posts/outfit-monochrome-fall-01',
      media: [
        {
          id: 'media-1',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/coat_wool_01',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-2',
      publicId: 'quiet-luxury-daily-02',
      title: 'Quiet Luxury Aesthetic in Daily Life',
      content: 'Tone beige & kem sữa luôn là bảng màu yêu thích khi muốn tạo cảm giác nhẹ nhàng, tinh tế nhưng vẫn có gu riêng.',
      postType: 'OUTFIT',
      userId: 'user-02',
      username: 'lananh.curator',
      firstName: 'Lan Anh',
      lastName: 'Trần',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=300&auto=format&fit=crop',
      likeCount: 285,
      commentCount: 34,
      isLiked: true,
      isDeleted: false,
      createdAt: '2026-09-23T14:15:00.000Z',
      updatedAt: '2026-09-23T14:15:00.000Z',
      sharePath: '/posts/quiet-luxury-daily-02',
      media: [
        {
          id: 'media-2',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/knit_skirt_02',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-3',
      publicId: 'urban-utility-chic-03',
      title: 'Urban Utility Chic Style',
      content: 'Blazer cắt cúp kết hợp cùng túi utility đeo chéo và sneakers retro. Sự cân bằng hoàn hảo giữa tính thanh lịch công sở và năng động đường phố.',
      postType: 'OUTFIT',
      userId: 'user-03',
      username: 'marcus.tailoring',
      firstName: 'Marcus',
      lastName: 'Vu',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
      likeCount: 96,
      commentCount: 12,
      isLiked: false,
      isDeleted: false,
      createdAt: '2026-09-23T08:00:00.000Z',
      updatedAt: '2026-09-23T08:00:00.000Z',
      sharePath: '/posts/urban-utility-chic-03',
      media: [
        {
          id: 'media-3',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/blazer_utility_03',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-4',
      publicId: 'vintage-90s-leather-04',
      title: 'Archive 90s Leather Jacket Vibe',
      content: 'Chiếc áo da vintage dáng boxy săn được ở tiệm đồ cổ kết hợp cùng quần denim wash bạc ống đứng. Vừa bền vững vừa không sợ đụng hàng!',
      postType: 'OUTFIT',
      userId: 'user-04',
      username: 'minhtriet.archive',
      firstName: 'Minh',
      lastName: 'Triết',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
      likeCount: 412,
      commentCount: 53,
      isLiked: true,
      isDeleted: false,
      createdAt: '2026-09-22T19:45:00.000Z',
      updatedAt: '2026-09-22T19:45:00.000Z',
      sharePath: '/posts/vintage-90s-leather-04',
      media: [
        {
          id: 'media-4',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/vintage_leather_04',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-5',
      publicId: 'desert-linen-layering-05',
      title: 'Linen Layering cho ngày cuối hạ',
      content: 'Chất liệu linen tự nhiên luôn mang lại cảm giác thoáng mát và tự do. Một set đồ ton-sur-ton màu cát sa mạc tạo nét mộc mạc cao cấp.',
      postType: 'OUTFIT',
      userId: 'user-05',
      username: 'thao.minimal',
      firstName: 'Thảo',
      lastName: 'Phạm',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=300&auto=format&fit=crop',
      likeCount: 178,
      commentCount: 21,
      isLiked: false,
      isDeleted: false,
      createdAt: '2026-09-22T11:20:00.000Z',
      updatedAt: '2026-09-22T11:20:00.000Z',
      sharePath: '/posts/desert-linen-layering-05',
      media: [
        {
          id: 'media-5',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/linen_set_05',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-6',
      publicId: 'tailored-blazer-casual-06',
      title: 'Tailored Blazer & Raw Denim Casual',
      content: 'Công thức không bao giờ lỗi mốt cho ngày làm việc lẫn cà phê cuối tuần: Blazer may đo chuẩn phom + áo thun trắng trơn + quần jeans ống suông.',
      postType: 'OUTFIT',
      userId: 'user-06',
      username: 'quynhanh.couture',
      firstName: 'Quỳnh',
      lastName: 'Anh',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
      likeCount: 320,
      commentCount: 29,
      isLiked: false,
      isDeleted: false,
      createdAt: '2026-09-21T16:10:00.000Z',
      updatedAt: '2026-09-21T16:10:00.000Z',
      sharePath: '/posts/tailored-blazer-casual-06',
      media: [
        {
          id: 'media-6',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/blazer_casual_06',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-7',
      publicId: 'all-black-smart-casual-07',
      title: 'All-Black Contemporary Look',
      content: 'Sự kết hợp giữa các sắc độ đen khác nhau: áo cổ lọ len dệt kim, áo khoác bomber kỹ thuật số và quần tây ống suông xếp ly.',
      postType: 'OUTFIT',
      userId: 'user-07',
      username: 'kien.atelier',
      firstName: 'Kiên',
      lastName: 'Hoàng',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=300&auto=format&fit=crop',
      likeCount: 260,
      commentCount: 15,
      isLiked: true,
      isDeleted: false,
      createdAt: '2026-09-21T07:45:00.000Z',
      updatedAt: '2026-09-21T07:45:00.000Z',
      sharePath: '/posts/all-black-smart-casual-07',
      media: [
        {
          id: 'media-7',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/all_black_07',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-8',
      publicId: 'silk-slip-dress-trench-08',
      title: 'Silk Slip Dress & Trench Coat',
      content: 'Sự mềm mại của lụa đối lập với nét đứng phom của trench coat cổ điển tạo nên vẻ ngoài nữ tính nhưng đầy độc lập và kiêu kỳ.',
      postType: 'OUTFIT',
      userId: 'user-08',
      username: 'charlotte.le',
      firstName: 'Charlotte',
      lastName: 'Lê',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=300&auto=format&fit=crop',
      likeCount: 512,
      commentCount: 42,
      isLiked: false,
      isDeleted: false,
      createdAt: '2026-09-20T20:30:00.000Z',
      updatedAt: '2026-09-20T20:30:00.000Z',
      sharePath: '/posts/silk-slip-dress-trench-08',
      media: [
        {
          id: 'media-8',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/silk_trench_08',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-9',
      publicId: 'clean-streetwear-oxford-09',
      title: 'Clean Streetwear with Raw Denim',
      content: 'Quần raw denim cùng sơ mi oxford kẻ sọc dáng rộng và giày loafer thủ công. Tối giản, không cầu kỳ nhưng luôn cuốn hút.',
      postType: 'OUTFIT',
      userId: 'user-09',
      username: 'vietan.lookbook',
      firstName: 'Việt',
      lastName: 'An',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=300&auto=format&fit=crop',
      likeCount: 189,
      commentCount: 16,
      isLiked: false,
      isDeleted: false,
      createdAt: '2026-09-20T10:15:00.000Z',
      updatedAt: '2026-09-20T10:15:00.000Z',
      sharePath: '/posts/clean-streetwear-oxford-09',
      media: [
        {
          id: 'media-9',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/streetwear_denim_09',
          sortOrder: 0,
        },
      ],
      items: [],
    },
    {
      id: 'post-10',
      publicId: 'tweed-jacket-contemporary-10',
      title: 'Tweed Jacket Contemporary Twist',
      content: 'Biến tấu chiếc áo khoác dạ tweed kinh điển trở nên trẻ trung hơn khi phối cùng quần ống suông cạp cao và túi xách baguette tối giản.',
      postType: 'OUTFIT',
      userId: 'user-10',
      username: 'haianh.style',
      firstName: 'Hải',
      lastName: 'Anh',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=300&auto=format&fit=crop',
      likeCount: 345,
      commentCount: 27,
      isLiked: true,
      isDeleted: false,
      createdAt: '2026-09-19T17:00:00.000Z',
      updatedAt: '2026-09-19T17:00:00.000Z',
      sharePath: '/posts/tweed-jacket-contemporary-10',
      media: [
        {
          id: 'media-10',
          mediaType: 'IMAGE',
          mediaUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=1000&auto=format&fit=crop',
          publicId: 'community/tweed_jacket_10',
          sortOrder: 0,
        },
      ],
      items: [],
    },
  ],
};
